### ISSUE TITLE
Goal

### ISSUE THREAD

**Issue by miniflycn** [BetterJS/try-wrapper#1]
可定制的try-catch包裹，可通过自动化构建以及简单配置对项目代码进行try-catch包裹。

计划实现的功能：
- 可定制函数包裹
- 可定制是否对return的函数进行包裹
#### 基本原理

基于 [Mozilla parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) 规范的 AST 来解决try-catch线下可定制包裹问题。
#### 什么场景下你可能需要他
- 临时性错误跟踪，非临时性建议使用badjs
- 非类AMD规范下的跨域错误跟踪，类AMD模块下跨域错误代码跟踪建议使用tryjs
- 非侵入式错误跟踪，要完全杜绝对第三方代码的影响，故此时只能直接对自己的代码进行包裹

**Comment by 17biubiu** [comment]
如何在webpack中使用这个，对于每个组件进行包裹try..catch

**Comment by miniflycn** [comment]
自己做个plugin
